# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the IXXAT PCI CAN/CAN FD controller driver.
#

obj-$(CONFIG_CAN_IXXAT_PCI_ACTIVE) += ix_active_can.o
ix_active_can-y = ixxat_pci_core.o ixxat_pci_active.o ixxat_pci_active_fd.o

